### ISSUE TITLE
Can we update this so its compatible with latest active models?

### ISSUE THREAD

**Issue by ryano3000** [german/redis_orm#14]
redis-orm was resolved to 0.0.4, which depends on
      activemodel (~> 3.0.10)

**Comment by german** [comment]
Yep, just updated @ryano3000, please use new `0.8` version of the gem: https://rubygems.org/gems/redis_orm/versions/0.8

Please let me know if everything went fine? 

BTW how do you use this gem? I'll try to update it to be more up-to-date and fix existing errors.
